"""QR codes as inline SVG (no image files, crisp at any size, theme-proof)."""

import io

import qrcode
import qrcode.image.svg
from django.conf import settings
from django.urls import reverse
from django.utils.safestring import mark_safe


def svg(data: str, *, box_size: int = 10) -> str:
    img = qrcode.make(
        data,
        image_factory=qrcode.image.svg.SvgPathImage,
        box_size=box_size,
        border=2,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
    )
    buf = io.BytesIO()
    img.save(buf)
    out = buf.getvalue().decode()
    out = out[out.index("<svg") :]  # drop the XML prolog so it can be inlined
    return mark_safe(out.replace("<svg ", '<svg role="img" aria-label="QR code" class="qr" ', 1))  # noqa: S308 - generated by qrcode, no user HTML


def pass_url(booking) -> str:
    return settings.SITE_URL.rstrip("/") + reverse("checkins:pass", args=[booking.qr_token])


def door_url(resource) -> str:
    return settings.SITE_URL.rstrip("/") + reverse("checkins:here", args=[resource.code])
