# Generated by Django 5.2.17 on 2026-09-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField()),
                ('method', models.CharField(choices=[('resource_qr', 'Scanned the room/equipment QR'), ('pass_qr', 'Booking pass scanned by custodian'), ('app', 'Tapped check-in in app'), ('custodian', 'Checked in by custodian')], max_length=16)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('auto_checked_out', models.BooleanField(default=False)),
                ('minutes_released', models.PositiveIntegerField(default=0, help_text='Time handed back by an early check-out')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='bookings.booking')),
                ('checked_in_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField()),
                ('released_minutes', models.PositiveIntegerField(default=0)),
                ('forgiven', models.BooleanField(default=False)),
                ('forgiven_reason', models.CharField(blank=True, max_length=240)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='no_show', to='bookings.booking')),
                ('forgiven_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_shows', to='catalogue.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_shows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['user', 'detected_at'], name='checkins_no_user_id_76dcde_idx')],
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=240)),
                ('tier_label', models.CharField(blank=True, max_length=80)),
                ('automatic', models.BooleanField(default=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='restriction_ordered')],
            },
        ),
    ]
