# Generated by Django 5.2.17 on 2026-09-30 16:22

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_extensions_and_default_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('school', models.CharField(blank=True, max_length=160)),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('custodian', 'Resource Custodian'), ('dept_head', 'Head of Department'), ('facility_manager', 'Facility Manager'), ('admin', 'Administrator')], db_index=True, default='student', max_length=24)),
                ('vid', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='VID')),
                ('section', models.CharField(blank=True, max_length=20)),
                ('programme', models.CharField(blank=True, max_length=160)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('calendar_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('failed_logins', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.department')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'permissions': [('book_resources', 'Can book resources'), ('book_recurring', 'Can create recurring bookings'), ('book_on_behalf', 'Can book on behalf of a class or group'), ('approve_bookings', 'Can decide approvals'), ('manage_resources', 'Can manage resources they are responsible for'), ('manage_maintenance', 'Can schedule maintenance'), ('manage_inventory', 'Can manage consumables and accessories'), ('view_department_analytics', 'Can view departmental utilisation'), ('view_campus_analytics', 'Can view campus-wide utilisation'), ('configure_policy', 'Can configure rules, quotas and workflows'), ('manage_timetable', 'Can publish timetables'), ('manage_users', 'Can manage users and roles'), ('forgive_no_shows', 'Can forgive no-shows and lift restrictions'), ('view_audit_log', 'Can view the audit log')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_department_code'),
        ),
    ]
