# Generated by Django 5.2.17 on 2026-10-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.TextField(blank=True, help_text='TOTP secret, encrypted at rest (apps.accounts.mfa)'),
        ),
    ]
