# Generated by Django 5.2.17 on 2026-10-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_mfa"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_last_step",
            field=models.BigIntegerField(
                blank=True,
                help_text="Last TOTP time step accepted (no replay)",
                null=True,
            ),
        ),
    ]
