# Generated by Django 5.2.17 on 2026-09-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='UMS term code, e.g. 26271', max_length=16)),
                ('name', models.CharField(max_length=80)),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
            ],
            options={
                'ordering': ['-starts'],
            },
        ),
        migrations.CreateModel(
            name='TimetablePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('source', models.CharField(default='csv', help_text='csv | p13-api | manual', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded'), ('failed', 'Failed')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('displaced_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='timetable.academicterm')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course_code', models.CharField(max_length=16)),
                ('course_title', models.CharField(blank=True, max_length=160)),
                ('section', models.CharField(blank=True, max_length=24)),
                ('faculty', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(default='Lecture', help_text='Lecture | Practical | Tutorial', max_length=16)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='catalogue.resource')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timetablepublication')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_term_code'),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.CheckConstraint(condition=models.Q(('starts__lt', models.F('ends'))), name='term_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='timetablepublication',
            constraint=models.UniqueConstraint(fields=('term', 'version'), name='uniq_publication_version'),
        ),
        migrations.AddConstraint(
            model_name='timetablepublication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('term',), name='one_published_timetable_per_term'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='entry_times_ordered'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='entry_weekday_valid'),
        ),
    ]
