# Generated by Django 5.2.17 on 2026-09-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=40)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SweepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('affected', models.PositiveIntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ok', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task', '-started_at'], name='core_sweepr_task_46b3cc_idx')],
            },
        ),
    ]
