# Generated by Django 5.2.17 on 2026-09-30 16:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('requester_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('custodian', 'Resource Custodian'), ('dept_head', 'Head of Department'), ('facility_manager', 'Facility Manager'), ('admin', 'Administrator')], max_length=24), blank=True, default=list, help_text='Applies when the person booking holds one of these roles. Empty = any role.', size=None)),
                ('min_attendees', models.PositiveIntegerField(blank=True, help_text='Only when attendees ≥ this', null=True)),
                ('min_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Only when longer than this', null=True)),
                ('auto_approve', models.BooleanField(default=False, help_text='Matching bookings are confirmed instantly')),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='catalogue.resource')),
                ('resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='catalogue.resourcetype')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('approver_role', models.CharField(choices=[('custodian', 'Resource custodian'), ('dept_head', 'Head of owning department'), ('facility_manager', 'Facility manager'), ('admin', 'Administrator'), ('user', 'Named person')], max_length=24)),
                ('sla_hours', models.PositiveSmallIntegerField(default=24)),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalworkflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField()),
                ('approver_role', models.CharField(choices=[('custodian', 'Resource custodian'), ('dept_head', 'Head of owning department'), ('facility_manager', 'Facility manager'), ('admin', 'Administrator'), ('user', 'Named person')], max_length=24)),
                ('decision', models.CharField(choices=[('waiting', 'Waiting'), ('pending', 'Awaiting decision'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Not required')], db_index=True, default='waiting', max_length=10)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='bookings.booking')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_decided', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='approvals.approvalworkflow')),
            ],
            options={
                'ordering': ['booking', 'step_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='approvalworkflow',
            constraint=models.CheckConstraint(condition=models.Q(('resource__isnull', False), ('resource_type__isnull', False), _negated=True), name='workflow_resource_or_type_not_both'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='uniq_step_order'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approver_role', 'user'), _negated=True), ('approver_user__isnull', False), _connector='OR'), name='step_named_user_when_user_role'),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(fields=('booking', 'step_order'), name='uniq_approval_step'),
        ),
    ]
