# Generated by Django 5.2.17 on 2026-09-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('accessory', 'Accessory (returned)'), ('consumable', 'Consumable (used up)')], max_length=12)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('quantity_total', models.PositiveIntegerField(default=0, help_text='Owned (accessories) / last restock (consumables)')),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('max_per_booking', models.PositiveIntegerField(default=10)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalogue.resource')),
                ('resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalogue.resourcetype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('issued', 'Issued'), ('returned', 'Returned'), ('consumed', 'Consumed'), ('cancelled', 'Cancelled'), ('lost', 'Lost / damaged')], db_index=True, default='reserved', max_length=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='bookings.booking')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(max_length=24)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issuance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.issuance')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('institution', 'sku'), name='uniq_item_sku'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'consumable'), ('quantity_available__lte', models.F('quantity_total')), _connector='OR'), name='item_available_le_total_for_accessories'),
        ),
        migrations.AddConstraint(
            model_name='issuance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='issuance_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='issuance',
            constraint=models.UniqueConstraint(fields=('booking', 'item'), name='uniq_issuance_item_per_booking'),
        ),
    ]
