# Generated by Django 5.2.17 on 2026-10-01 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def confirm_existing_critical(apps, schema_editor):
    """Critical reports filed before SEC-02 already took their resource offline; record them as confirmed."""
    BreakdownReport = apps.get_model("maintenance", "BreakdownReport")
    for report in BreakdownReport.objects.filter(severity="critical", confirmed_at__isnull=True):
        report.confirmed_at = report.created_at
        report.confirmed_by_id = report.reported_by_id
        report.save(update_fields=["confirmed_at", "confirmed_by"])


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="breakdownreport",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="breakdownreport",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(confirm_existing_critical, migrations.RunPython.noop),
    ]
