# Generated by Django 5.2.17 on 2026-09-30 16:22

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_extensions_and_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('zone', models.CharField(blank=True, help_text='Campus zone, e.g. Academic Zone, Sports Complex', max_length=80)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('map_x', models.PositiveSmallIntegerField(default=50, help_text='Position on campus map (0-100)')),
                ('map_y', models.PositiveSmallIntegerField(default=50)),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('icon', models.CharField(default='check', max_length=40)),
                ('keywords', models.CharField(blank=True, help_text='Extra search terms', max_length=200)),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Human code, e.g. 34-301', max_length=32)),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=140)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('floor', models.CharField(blank=True, max_length=16)),
                ('room', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(choices=[('active', 'Active'), ('out_of_service', 'Out of service'), ('retired', 'Retired')], db_index=True, default='active', max_length=20)),
                ('status_note', models.CharField(blank=True, max_length=200)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.ImageField(blank=True, upload_to='resources/')),
                ('art', models.CharField(blank=True, help_text='Illustration key when no photo is uploaded', max_length=40)),
                ('is_bookable', models.BooleanField(default=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='catalogue.building')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='accounts.department')),
                ('features', models.ManyToManyField(blank=True, related_name='resources', to='catalogue.feature')),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
            ],
            options={
                'ordering': ['type__sort_order', 'building__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Custodian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodianships', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodians', to='catalogue.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalogue.resource')),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ResourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resources/gallery/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.resource')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('plural', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(choices=[('space', 'Space'), ('lab', 'Laboratory'), ('equipment', 'Equipment'), ('sports', 'Sports'), ('vehicle', 'Vehicle')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='box', max_length=40)),
                ('accent', models.CharField(default='orange', help_text='Design-system accent token', max_length=16)),
                ('allowed_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('custodian', 'Resource Custodian'), ('dept_head', 'Head of Department'), ('facility_manager', 'Facility Manager'), ('admin', 'Administrator')], max_length=24), blank=True, default=list, help_text='Roles allowed to book this type. Empty = everyone.', size=None)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='catalogue.resourcetype'),
        ),
        migrations.CreateModel(
            name='SavedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogue.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_building_code'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='uniq_feature_name'),
        ),
        migrations.AddConstraint(
            model_name='custodian',
            constraint=models.UniqueConstraint(fields=('resource', 'user'), name='uniq_custodian'),
        ),
        migrations.AddConstraint(
            model_name='resourcetype',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_resourcetype_code'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='resource_search_gin'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='resource_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['type', 'status'], name='catalogue_r_type_id_14c921_idx'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_resource_code'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('institution', 'slug'), name='uniq_resource_slug'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='resource_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='savedresource',
            constraint=models.UniqueConstraint(fields=('user', 'resource'), name='uniq_saved_resource'),
        ),
    ]
