# Generated by Django 5.2.17 on 2026-09-30 16:22

import django.contrib.postgres.constraints
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.bookings.models
import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('core', '0002_extensions_and_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=8)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, size=None)),
                ('start_date', models.DateField()),
                ('until_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('group_label', models.CharField(blank=True, max_length=120)),
                ('created_count', models.PositiveSmallIntegerField(default=0)),
                ('skipped', models.JSONField(blank=True, default=list, help_text='Occurrences not booked and why')),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_series', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='catalogue.resource')),
            ],
            options={
                'verbose_name_plural': 'booking series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.bookings.models._reference, editable=False, max_length=12, unique=True)),
                ('group_label', models.CharField(blank=True, help_text='Class / section / club this is for', max_length=120)),
                ('title', models.CharField(max_length=140)),
                ('attendees', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('approved', 'Confirmed'), ('checked_in', 'In use'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('no_show', 'Released · no-show')], db_index=True, default='pending', max_length=16)),
                ('qr_token', models.CharField(default=apps.bookings.models._qr_token, editable=False, max_length=32, unique=True)),
                ('requires_checkin', models.BooleanField(default=True)),
                ('checkin_grace_minutes', models.PositiveSmallIntegerField(default=15)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('status_reason', models.CharField(blank=True, max_length=240)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('checkin_nudge_sent_at', models.DateTimeField(blank=True, null=True)),
                ('booked_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_made', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalogue.resource')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.bookingseries')),
            ],
            options={
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('kind', models.CharField(choices=[('booking', 'Booking'), ('class', 'Timetabled class'), ('maintenance', 'Maintenance')], max_length=16)),
                ('source_type', models.CharField(blank=True, help_text='For non-booking claims, e.g. timetable_entry', max_length=32)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='bookings.booking')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='catalogue.resource')),
            ],
            options={
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='BookingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('outcome', models.CharField(choices=[('booked', 'Booked'), ('conflict', 'Slot taken'), ('timetable', 'Timetabled class'), ('maintenance', 'Maintenance'), ('blackout', 'Blackout'), ('closed', 'Outside hours'), ('quota', 'Quota exceeded'), ('restricted', 'User restricted'), ('policy', 'Policy violation'), ('forbidden', 'Not permitted')], db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='catalogue.resource')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['resource', 'created_at'], name='bookings_bo_resourc_7f64d0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bookingseries',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('until_date'))), name='series_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='bookingseries',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='series_times_ordered'),
        ),
        migrations.AddConstraint(
            model_name='bookingseries',
            constraint=models.CheckConstraint(condition=models.Q(('interval__gte', 1)), name='series_interval_positive'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_for', 'status'], name='bookings_bo_booked__432950_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['resource', 'status'], name='bookings_bo_resourc_636658_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('pending', 'approved', 'checked_in'))), expressions=[('resource', '='), ('period', '&&')], name='booking_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('period__isempty', False), ('period__lower_inf', False), ('period__upper_inf', False)), name='booking_period_bounded'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('attendees__gte', 1)), name='booking_attendees_positive'),
        ),
        migrations.AddIndex(
            model_name='bookingslot',
            index=models.Index(fields=['source_type', 'source_id'], name='bookings_bo_source__f29dee_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingslot',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('resource', '='), ('period', '&&')], name='slot_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='bookingslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('kind', 'booking')), models.Q(models.Q(('kind', 'booking'), _negated=True), ('booking__isnull', True)), _connector='OR'), name='slot_booking_kind_has_booking'),
        ),
        migrations.AddConstraint(
            model_name='bookingslot',
            constraint=models.CheckConstraint(condition=models.Q(('period__isempty', False), ('period__lower_inf', False), ('period__upper_inf', False)), name='slot_period_bounded'),
        ),
    ]
