# Generated by Django 5.2.17 on 2026-09-30 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open_minutes', models.PositiveIntegerField(default=0, help_text='Bookable supply after hours, blackouts, maintenance')),
                ('class_minutes', models.PositiveIntegerField(default=0)),
                ('maintenance_minutes', models.PositiveIntegerField(default=0)),
                ('booked_minutes', models.PositiveIntegerField(default=0)),
                ('used_minutes', models.PositiveIntegerField(default=0, help_text='Booked minutes that were checked into')),
                ('released_minutes', models.PositiveIntegerField(default=0, help_text='No-show / early check-out time returned')),
                ('bookings', models.PositiveIntegerField(default=0)),
                ('no_shows', models.PositiveIntegerField(default=0)),
                ('cancellations', models.PositiveIntegerField(default=0)),
                ('denied_attempts', models.PositiveIntegerField(default=0, help_text='Unmet demand: attempts refused for lack of supply')),
                ('hourly_booked', models.JSONField(blank=True, default=list, help_text='24 buckets of booked minutes')),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='catalogue.resource')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('resource', 'date'), name='uniq_snapshot_resource_date')],
            },
        ),
    ]
