# Generated by Django 5.2.17 on 2026-09-30 16:22

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('core', '0002_extensions_and_default_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('campus', 'Whole campus'), ('type', 'Resource type'), ('resource', 'Single resource')], default='type', max_length=12)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opens', models.TimeField()),
                ('closes', models.TimeField()),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='catalogue.resource')),
                ('resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='catalogue.resourcetype')),
            ],
            options={
                'ordering': ['weekday', 'opens'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('resource__isnull', True), ('resource_type__isnull', True), ('scope', 'campus')), models.Q(('resource__isnull', True), ('resource_type__isnull', False), ('scope', 'type')), models.Q(('resource__isnull', False), ('scope', 'resource')), _connector='OR'), name='hours_scope_consistent'), models.CheckConstraint(condition=models.Q(('opens__lt', models.F('closes'))), name='hours_open_before_close')],
            },
        ),
        migrations.CreateModel(
            name='Blackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('kind', models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Examination period'), ('event', 'University event'), ('restricted', 'Restricted period')], default='holiday', max_length=16)),
                ('scope', models.CharField(choices=[('campus', 'Whole campus'), ('type', 'Resource type'), ('resource', 'Single resource')], default='campus', max_length=12)),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('exempt_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('custodian', 'Resource Custodian'), ('dept_head', 'Head of Department'), ('facility_manager', 'Facility Manager'), ('admin', 'Administrator')], max_length=24), blank=True, default=list, size=None)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='catalogue.building')),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='catalogue.resource')),
                ('resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='catalogue.resourcetype')),
            ],
            options={
                'ordering': ['period'],
                'indexes': [models.Index(fields=['scope'], name='rules_black_scope_493909_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('resource__isnull', True), ('resource_type__isnull', True), ('scope', 'campus')), models.Q(('resource__isnull', True), ('resource_type__isnull', False), ('scope', 'type')), models.Q(('resource__isnull', False), ('scope', 'resource')), _connector='OR'), name='blackout_scope_consistent')],
            },
        ),
        migrations.CreateModel(
            name='BookingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('campus', 'Whole campus'), ('type', 'Resource type'), ('resource', 'Single resource')], default='type', max_length=12)),
                ('slot_minutes', models.PositiveSmallIntegerField(default=30)),
                ('min_duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('max_duration_minutes', models.PositiveSmallIntegerField(default=180)),
                ('lead_time_minutes', models.PositiveIntegerField(default=0, help_text='Minimum notice before start')),
                ('max_advance_days', models.PositiveSmallIntegerField(default=30, help_text='How far ahead bookings open')),
                ('requires_checkin', models.BooleanField(default=True)),
                ('checkin_opens_minutes', models.PositiveSmallIntegerField(default=15, help_text='Check-in opens this long before start')),
                ('checkin_grace_minutes', models.PositiveSmallIntegerField(default=15, help_text='Auto-release after this long without check-in')),
                ('enforce_capacity', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='catalogue.resource')),
                ('resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='catalogue.resourcetype')),
            ],
            options={
                'verbose_name_plural': 'booking policies',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('resource__isnull', True), ('resource_type__isnull', True), ('scope', 'campus')), models.Q(('resource__isnull', True), ('resource_type__isnull', False), ('scope', 'type')), models.Q(('resource__isnull', False), ('scope', 'resource')), _connector='OR'), name='policy_scope_consistent'), models.CheckConstraint(condition=models.Q(('min_duration_minutes__lte', models.F('max_duration_minutes'))), name='policy_duration_order'), models.CheckConstraint(condition=models.Q(('slot_minutes__gte', 5)), name='policy_slot_positive')],
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('custodian', 'Resource Custodian'), ('dept_head', 'Head of Department'), ('facility_manager', 'Facility Manager'), ('admin', 'Administrator')], max_length=24)),
                ('period', models.CharField(choices=[('day', 'per day'), ('week', 'per week'), ('month', 'per month')], default='week', max_length=8)),
                ('max_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('max_bookings', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='accounts.department')),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
                ('resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='catalogue.resourcetype')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', False), ('role', '')), models.Q(models.Q(('role', ''), _negated=True), ('department__isnull', True)), _connector='OR'), name='quota_targets_role_xor_department'), models.CheckConstraint(condition=models.Q(('max_hours__isnull', False), ('max_bookings__isnull', False), _connector='OR'), name='quota_has_a_limit')],
            },
        ),
        migrations.CreateModel(
            name='RestrictionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_shows', models.PositiveSmallIntegerField(help_text='Unforgiven no-shows within the window')),
                ('window_days', models.PositiveSmallIntegerField(default=30)),
                ('restrict_days', models.PositiveSmallIntegerField(default=0, help_text='0 = warning only')),
                ('label', models.CharField(max_length=80)),
                ('institution', models.ForeignKey(default=apps.core.models.default_institution_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.institution')),
            ],
            options={
                'ordering': ['no_shows'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'no_shows'), name='uniq_restriction_tier')],
            },
        ),
    ]
