# Generated by Django 5.2.17 on 2026-09-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('booking_confirmed', 'Booking confirmed'), ('approval_required', 'Approval required'), ('approval_pending', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reminder', 'Starting soon'), ('checkin_open', 'Check-in open'), ('auto_released', 'Auto-released'), ('restricted', 'Booking restricted'), ('maintenance', 'Maintenance scheduled'), ('unavailable', 'Resource unavailable'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('stock_low', 'Stock low'), ('breakdown', 'Breakdown reported'), ('series', 'Recurring booking')], max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=240)),
                ('tone', models.CharField(default='info', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
    ]
